### PR TITLE
Text hash only

### PR DESCRIPTION
**Pull request by jongacnik**
Alrighty, this is just the updated js which adds the text-hash functionality

### CODE REVIEW

**Comment by nicinabox** [comment]
This looks great! I'm going to review it thoroughly this afternoon.

**Comment by jongacnik** [comment]
Awesome. I think the weakest thing about it right now is if text-hashes are enabled and no data-href is provided on a slide element, that hash will return as undefined and things start to get a little wonky. For my purposes I knew I was always going to have data-href attributes, but I think a more graceful solution is probably to use the text-hash if a data-href is provided, otherwise use index hash.

**Comment by nicinabox** [comment]
@amongiants Sorry, I still haven't had time to review this and I'm out of town this weekend. I haven't forgotten about it, just TONS going on. Promise to get back to this.

**Comment by nicinabox** [comment]
@amongiants Your commits seem to be gone?

**Comment by jongacnik** [comment]
@nicinabox Hmm, you are right. Looks like `src/jquery.superslides.coffee` is the updated version to support text-hashes though. I don't have time right yet to add a commit and submit new pull.

**Comment by nicinabox** [comment]
Okay, before you do that, 0.6.0 on master is the latest code and will be released next week. It's a full port from coffeescript back to vanilla js. If you don't add it by next week, I probably will.

**Comment by nicinabox** [comment]
I just added it. Gets picked up automatically, no need for configuration.

**Pull request closed without merging**
