### PR TITLE
fix pagination link url

### PR DESCRIPTION
**Pull request by ayarulin**

### CODE REVIEW

**Comment by nicinabox** [comment]
Thanks @AdRulz!

**Comment by ayarulin** [comment]
Update: fix the bug when already have a hash in url

**Comment by nicinabox** [comment]
I was reading more about this. Apparently multiple hashes is not a valid URL. Plus, I can't reliably pull the slide number out of a URL with multiple hashes, so I opted not to include it in 0.5.0.

Can you give a use case for this? Perhaps there's another way to go about it.

**Comment by ayarulin** [comment]
I have found a bug in my previous pull-request. I've used window.location.href, so if in the URL already is a hash (index.php#1), link was created with a another hash above ( index.php#1#2). My last commit fix this.

**Pull request merged**
